export const JARGON: Record<string, string> = {
  'DCT':    'Dual Clutch Transmission — a fast-shifting automatic. Can get hot in heavy city traffic.',
  'IVT':    'Intelligent Variable Transmission — Hyundai\'s CVT variant. Smooth city drive, average highway feel.',
  'CVT':    'Continuously Variable Transmission — no fixed gears. Smooth but can feel "rubbery" at highway speeds.',
  'DSG':    'Direct Shift Gearbox — Volkswagen/Skoda\'s 6-speed DCT. Fast and efficient.',
  'ADAS':   'Advanced Driver Assistance Systems — semi-autonomous safety features like auto-braking and lane assist.',
  'TPMS':   'Tyre Pressure Monitoring System — alerts you when tyre pressure is too low.',
  'EBD':    'Electronic Brake Distribution — distributes braking force across all 4 wheels for better stopping.',
  'ESP':    'Electronic Stability Programme — prevents the car from skidding by controlling individual wheel brakes.',
  'ABS':    'Anti-lock Braking System — prevents wheels from locking during emergency braking.',
  'HAC':    'Hill Assist Control — holds the car on a slope for ~2 seconds to prevent rollback.',
  'DRL':    'Daytime Running Lights — always-on lights for visibility during the day.',
  'HUD':    'Head-Up Display — projects speed and navigation info onto the windscreen.',
  'ORVM':   'Outside Rear View Mirror.',
  'IRVM':   'Inside Rear View Mirror.',
  'BS6':    'Bharat Stage 6 emission standard — India\'s current cleanest fuel standard.',
  'MID':    'Multi-Information Display — small screen inside the instrument cluster.',
  'OTA':    'Over-The-Air updates — car software updated via Wi-Fi like a smartphone.',
  'FWD':    'Front Wheel Drive — engine power sent to front wheels only.',
  'AWD':    'All Wheel Drive — power sent to all four wheels for better traction.',
  'Nm':     'Newton-metres — the unit of torque (rotational pulling power).',
  'bhp':    'Brake Horsepower — the unit of engine power output.',
  'KMPL':   'Kilometres Per Litre — fuel efficiency measurement.',
  'ARAI':   'Automotive Research Association of India — official fuel efficiency testing body.',
}
